In [2]:
%pip install pandas
%pip install -U scikit-learn
%pip install openpyxl
%pip install xlrd

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [3]:
%pip list

Package            Version
------------------ -----------
asttokens          2.4.1
comm               0.2.2
debugpy            1.6.7
decorator          5.1.1
et-xmlfile         1.1.0
exceptiongroup     1.2.0
executing          2.0.1
importlib_metadata 7.1.0
ipykernel          6.29.3
ipython            8.22.2
jedi               0.19.1
joblib             1.3.2
jupyter_client     8.6.1
jupyter_core       5.7.2
matplotlib-inline  0.1.6
nest_asyncio       1.6.0
numpy              1.26.4
openpyxl           3.1.2
packaging          24.0
pandas             2.2.1
parso              0.8.3
pexpect            4.9.0
pickleshare        0.7.5
pip                23.3.1
platformdirs       4.2.0
prompt-toolkit     3.0.42
psutil             5.9.8
ptyprocess         0.7.0
pure-eval          0.2.2
Pygments           2.17.2
python-dateutil    2.9.0
pytz               2024.1
pyzmq              25.1.2
scikit-learn       1.4.1.post1
scipy              1.12.0
setuptools         68.2.2
six                1.16.0


# Библиотеки


In [4]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

# Данные


In [5]:
data2 = pd.read_excel("data1.xls", skiprows=3)
data2.head(5)

Unnamed: 0                         Unnamed: 1        Unnamed: 2  \
0  Вторичный рынок жилья               Российская Федерация  Все типы квартир   
1  Вторичный рынок жилья      Центральный федеральный округ  Все типы квартир   
2  Вторичный рынок жилья               Белгородская область  Все типы квартир   
3  Вторичный рынок жилья                   Брянская область  Все типы квартир   
4  Вторичный рынок жилья               Владимирская область  Все типы квартир   

   I квартал  II квартал  III квартал  IV квартал  I квартал.1  II квартал.1  \
0   61067.46    61903.26     63916.54    66711.56     67826.22      70789.70   
1   77463.56    79351.81     84416.55    90211.47     85132.83      90244.73   
2   43626.87    43674.93     45828.69    49021.49     53503.09      57416.53   
3   34963.76    34737.38     35276.76    36274.28     37975.21      38304.05   
4   43153.26    42349.68     43224.33    44295.37     48438.50      54992.89   

   III квартал.1  IV квартал.1  I квартал.2  II квартал.2  III квартал.2  \
0       73224.95      76686.26     89867.64      91637.43       92892.27   
1       94859.13      98406.68    113156.72     116164.27      117221.46   
2       57862.36      61141.76     82428.50      84193.74       78649.84   
3       38461.54      39406.97     56281.50      56382.89       57092.53   
4       59574.40      62250.92     70020.42      72221.10       72048.66   

   IV квартал.2  I квартал.3  II квартал.3  III квартал.3  IV квартал.3  
0      94362.82     90891.50      92363.00       94526.47      97418.39  
1     119041.20     88683.22      90037.21       92089.96      93246.58  
2      80354.32     75044.95      74399.72       74035.93      74350.51  
3      57679.33     66225.23      66155.28       66321.26      65800.61  
4      74573.84     84450.49      86096.61       86172.29      88648.98

In [6]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(data2):
    # Drop column: 'Unnamed: 2'
    data2 = data2.drop(columns=['Unnamed: 2'])
    # Drop column: 'Unnamed: 0'
    data2 = data2.drop(columns=['Unnamed: 0'])
    # Drop rows with missing data across all columns
    data2 = data2.dropna()
    return data2

data2_clean = clean_data(data2.copy())
data2_clean.head()

Unnamed: 1  I квартал  II квартал  III квартал  \
0               Российская Федерация   61067.46    61903.26     63916.54   
1      Центральный федеральный округ   77463.56    79351.81     84416.55   
2               Белгородская область   43626.87    43674.93     45828.69   
3                   Брянская область   34963.76    34737.38     35276.76   
4               Владимирская область   43153.26    42349.68     43224.33   

   IV квартал  I квартал.1  II квартал.1  III квартал.1  IV квартал.1  \
0    66711.56     67826.22      70789.70       73224.95      76686.26   
1    90211.47     85132.83      90244.73       94859.13      98406.68   
2    49021.49     53503.09      57416.53       57862.36      61141.76   
3    36274.28     37975.21      38304.05       38461.54      39406.97   
4    44295.37     48438.50      54992.89       59574.40      62250.92   

   I квартал.2  II квартал.2  III квартал.2  IV квартал.2  I квартал.3  \
0     89867.64      91637.43       92892.27      94362.82     90891.50   
1    113156.72     116164.27      117221.46     119041.20     88683.22   
2     82428.50      84193.74       78649.84      80354.32     75044.95   
3     56281.50      56382.89       57092.53      57679.33     66225.23   
4     70020.42      72221.10       72048.66      74573.84     84450.49   

   II квартал.3  III квартал.3  IV квартал.3  
0      92363.00       94526.47      97418.39  
1      90037.21       92089.96      93246.58  
2      74399.72       74035.93      74350.51  
3      66155.28       66321.26      65800.61  
4      86096.61       86172.29      88648.98

In [7]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(data2_clean):
    # Rename column 'Unnamed: 1' to 'Место'
    data2_clean = data2_clean.rename(columns={'Unnamed: 1': 'Место'})
    return data2_clean

data2_clean_1 = clean_data(data2_clean.copy())
data2_clean_1.head()

Место  I квартал  II квартал  III квартал  \
0               Российская Федерация   61067.46    61903.26     63916.54   
1      Центральный федеральный округ   77463.56    79351.81     84416.55   
2               Белгородская область   43626.87    43674.93     45828.69   
3                   Брянская область   34963.76    34737.38     35276.76   
4               Владимирская область   43153.26    42349.68     43224.33   

   IV квартал  I квартал.1  II квартал.1  III квартал.1  IV квартал.1  \
0    66711.56     67826.22      70789.70       73224.95      76686.26   
1    90211.47     85132.83      90244.73       94859.13      98406.68   
2    49021.49     53503.09      57416.53       57862.36      61141.76   
3    36274.28     37975.21      38304.05       38461.54      39406.97   
4    44295.37     48438.50      54992.89       59574.40      62250.92   

   I квартал.2  II квартал.2  III квартал.2  IV квартал.2  I квартал.3  \
0     89867.64      91637.43       92892.27      94362.82     90891.50   
1    113156.72     116164.27      117221.46     119041.20     88683.22   
2     82428.50      84193.74       78649.84      80354.32     75044.95   
3     56281.50      56382.89       57092.53      57679.33     66225.23   
4     70020.42      72221.10       72048.66      74573.84     84450.49   

   II квартал.3  III квартал.3  IV квартал.3  
0      92363.00       94526.47      97418.39  
1      90037.21       92089.96      93246.58  
2      74399.72       74035.93      74350.51  
3      66155.28       66321.26      65800.61  
4      86096.61       86172.29      88648.98

In [8]:
data2_clean_1 = data2_clean_1.drop(0, axis=0)
data2_clean_1.head(5)

Место  I квартал  II квартал  III квартал  \
1      Центральный федеральный округ   77463.56    79351.81     84416.55   
2               Белгородская область   43626.87    43674.93     45828.69   
3                   Брянская область   34963.76    34737.38     35276.76   
4               Владимирская область   43153.26    42349.68     43224.33   
5                Воронежская область   47430.28    47992.56     48246.48   

   IV квартал  I квартал.1  II квартал.1  III квартал.1  IV квартал.1  \
1    90211.47     85132.83      90244.73       94859.13      98406.68   
2    49021.49     53503.09      57416.53       57862.36      61141.76   
3    36274.28     37975.21      38304.05       38461.54      39406.97   
4    44295.37     48438.50      54992.89       59574.40      62250.92   
5    50626.94     53988.88      52849.96       58479.03      60573.47   

   I квартал.2  II квартал.2  III квартал.2  IV квартал.2  I квартал.3  \
1    113156.72     116164.27      117221.46     119041.20     88683.22   
2     82428.50      84193.74       78649.84      80354.32     75044.95   
3     56281.50      56382.89       57092.53      57679.33     66225.23   
4     70020.42      72221.10       72048.66      74573.84     84450.49   
5     68952.68      72863.22       73295.43      81299.25     75883.02   

   II квартал.3  III квартал.3  IV квартал.3  
1      90037.21       92089.96      93246.58  
2      74399.72       74035.93      74350.51  
3      66155.28       66321.26      65800.61  
4      86096.61       86172.29      88648.98  
5      73669.29       75096.51      76506.25

In [9]:
X = data2_clean_1.drop(['Место'], axis=1)
Y = data2_clean_1['Место']
X.head(5)

I квартал  II квартал  III квартал  IV квартал  I квартал.1  II квартал.1  \
1   77463.56    79351.81     84416.55    90211.47     85132.83      90244.73   
2   43626.87    43674.93     45828.69    49021.49     53503.09      57416.53   
3   34963.76    34737.38     35276.76    36274.28     37975.21      38304.05   
4   43153.26    42349.68     43224.33    44295.37     48438.50      54992.89   
5   47430.28    47992.56     48246.48    50626.94     53988.88      52849.96   

   III квартал.1  IV квартал.1  I квартал.2  II квартал.2  III квартал.2  \
1       94859.13      98406.68    113156.72     116164.27      117221.46   
2       57862.36      61141.76     82428.50      84193.74       78649.84   
3       38461.54      39406.97     56281.50      56382.89       57092.53   
4       59574.40      62250.92     70020.42      72221.10       72048.66   
5       58479.03      60573.47     68952.68      72863.22       73295.43   

   IV квартал.2  I квартал.3  II квартал.3  III квартал.3  IV квартал.3  
1     119041.20     88683.22      90037.21       92089.96      93246.58  
2      80354.32     75044.95      74399.72       74035.93      74350.51  
3      57679.33     66225.23      66155.28       66321.26      65800.61  
4      74573.84     84450.49      86096.61       86172.29      88648.98  
5      81299.25     75883.02      73669.29       75096.51      76506.25

In [10]:
Y.head(5)

1        Центральный федеральный округ
2                 Белгородская область
3                     Брянская область
4                 Владимирская область
5                  Воронежская область
Name: Место, dtype: object

# **_Создание модели_**


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [11]:
len(Y)

183

In [18]:
print(Y_train.shape[0], X_train.shape[0])

122 122


In [19]:
kmeans = KMeans(n_clusters=Y_train.shape[0], random_state=42, n_init="auto").fit(X_train)
kmeans.labels_

array([ 35,  68,  79,   9,  56,  71, 121,  25,  32,  94,   6,  21,  88,
        17,  22, 100,  87,  85, 116,  30,  37,  49,  83,   3,  20,  90,
        53,  57,  50,  48,  62,  82,  38,  78,  54,  43,  96,  14,  64,
        47,  24,  65,   2,  33,  98,   0,  42,  10,  15,   4,  55, 115,
        74,  52,  60,  39,  72, 119,  66,   5,  11, 104,  61,  86, 120,
         1,  77,  76, 103,  81,  99, 101,  29,   7, 108,  80,   8,  58,
       107,  45, 106,  13,  36,  59,  26,  69,  89, 117,  95,  70, 114,
        67,  27,  18,  16,  34,  92, 118,  12,  91, 110,  84,  63,  28,
       113,  73,  46, 105, 102, 109,  41,  31,  93, 112,  19,  75,  23,
        51,  40,  97,  44, 111], dtype=int32)

In [39]:
kmeans.predict(X_test.iloc(axis=0)[[33]])

array([87], dtype=int32)

In [40]:
kmeans2 = KMeans(n_clusters=25, random_state=0, n_init="auto").fit(X)
kmeans2.labels_

array([ 7,  6, 15,  6,  6, 20,  6,  2, 20,  6, 23,  2,  6, 15, 20, 11, 11,
        6,  9,  7,  6,  6,  8, 11,  8, 20,  0,  8, 11,  2, 20, 22, 11,  6,
        2, 16, 10,  2,  2,  6, 13,  2,  6, 19,  2,  6,  2,  2, 20, 11, 11,
        2, 20, 21,  6,  6, 11, 20, 23, 15,  2,  6, 20, 20, 11, 15,  8,  0,
        8, 11, 20, 11, 16, 23,  6,  6,  6, 11,  6,  8,  6, 11, 23, 11,  8,
       13, 23,  5,  7, 23,  0, 14,  2, 21, 12,  0, 20, 20, 11, 20,  0,  6,
        6,  6, 12,  6, 11,  2, 20, 11, 11, 11,  3,  1, 16, 11,  8,  8,  6,
        0, 18,  2,  2, 17, 16,  0, 15, 23,  4,  0,  6,  0, 24, 15, 15, 19,
       19, 19, 15,  2, 20,  0, 16,  2, 20, 21, 11,  6,  0, 11,  4,  2, 11,
        0, 20,  6,  8,  2, 23,  8,  0, 21,  8,  6,  0,  6, 11,  8, 23,  0,
       16, 11,  0, 21, 11,  4, 21,  4, 12, 21, 21,  5, 14], dtype=int32)

In [41]:
kmeans2.labels_[0]

7

In [43]:
Y.iloc(axis=0)[0]

'    Центральный федеральный округ'

In [47]:
kmeans2.predict(X.iloc(axis=0)[[34]])

array([2], dtype=int32)

In [48]:
kmeans2

KMeans(n_clusters=25, random_state=0)

In [49]:
semi_ans = kmeans2.labels_

In [52]:
type(semi_ans)

numpy.ndarray

In [54]:
type(Y)

pandas.core.series.Series

In [56]:
np_y = Y.to_numpy()

In [57]:
np_y

array(['    Центральный федеральный округ',
       '        Белгородская область', '        Брянская область',
       '        Владимирская область', '        Воронежская область',
       '        Ивановская область', '        Калужская область',
       '        Костромская область', '        Курская область',
       '        Липецкая область', '        Московская область',
       '        Орловская область', '        Рязанская область',
       '        Смоленская область', '        Тамбовская область',
       '        Тверская область', '        Тульская область',
       '        Ярославская область',
       '        Город Москва столица Российской Федерации город федерального значения',
       '    Северо-Западный федеральный округ',
       '        Республика Карелия', '        Республика Коми',
       '        Архангельская область',
       '            Ненецкий автономный округ (Архангельская область)',
       '            Архангельская область (кроме Ненецкого автономного округа)

In [74]:
semi_ans

array([ 7,  6, 15,  6,  6, 20,  6,  2, 20,  6, 23,  2,  6, 15, 20, 11, 11,
        6,  9,  7,  6,  6,  8, 11,  8, 20,  0,  8, 11,  2, 20, 22, 11,  6,
        2, 16, 10,  2,  2,  6, 13,  2,  6, 19,  2,  6,  2,  2, 20, 11, 11,
        2, 20, 21,  6,  6, 11, 20, 23, 15,  2,  6, 20, 20, 11, 15,  8,  0,
        8, 11, 20, 11, 16, 23,  6,  6,  6, 11,  6,  8,  6, 11, 23, 11,  8,
       13, 23,  5,  7, 23,  0, 14,  2, 21, 12,  0, 20, 20, 11, 20,  0,  6,
        6,  6, 12,  6, 11,  2, 20, 11, 11, 11,  3,  1, 16, 11,  8,  8,  6,
        0, 18,  2,  2, 17, 16,  0, 15, 23,  4,  0,  6,  0, 24, 15, 15, 19,
       19, 19, 15,  2, 20,  0, 16,  2, 20, 21, 11,  6,  0, 11,  4,  2, 11,
        0, 20,  6,  8,  2, 23,  8,  0, 21,  8,  6,  0,  6, 11,  8, 23,  0,
       16, 11,  0, 21, 11,  4, 21,  4, 12, 21, 21,  5, 14], dtype=int32)

In [75]:
columns = ['Regions', 'rank']

In [72]:
print(np_y.shape, semi_ans.shape)

(183,) (183,)


In [76]:
df = pd.DataFrame({columns[0]: np_y, columns[1]: semi_ans})
df

Regions  rank
0        Центральный федеральный округ     7
1                 Белгородская область     6
2                     Брянская область    15
3                 Владимирская область     6
4                  Воронежская область     6
..                                 ...   ...
178                    Приморский край    12
179                   Хабаровский край    21
180                   Амурская область    21
181                Магаданская область     5
182                Сахалинская область    14

[183 rows x 2 columns]

In [83]:
from json import loads, dumps
df.to_json('model.json', orient='records', lines=True)

In [84]:
df.to_excel("output.xlsx")  

In [85]:
df.to_csv('out.csv', index=True)